spring:
  datasource:
    username: muzychka
    password: Taras2021
    url: jdbc:sqlserver://morfeusz.wszib.edu.pl:1433;databaseName=muzychka
  sql:
    init:
      mode: always
  flyway:
#    user: muzychka
#    password: Taras2021
#    url: jdbc:sqlserver://morfeusz.wszib.edu.pl:1433;databaseName=muzychka
#    locations: classpath:db/migrations
#    schemas: [muzychka]
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create-drop
